<a href="https://colab.research.google.com/github/AbhinavMsh/Ai-Data-Insights/blob/main/DS_act_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# --- Setup / Import ---
import numpy as np


# --- Section: Theory Examples ---

In [2]:
# np.zeros: 2D array
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
# np.arange: 1D range 0 to 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# np.arange: with float data type
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
# np.arange: with step size
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [6]:
# np.linspace: evenly spaced numbers
np.linspace(1., 4., 6)


array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [7]:
# np.indices: grid indices
np.indices((3, 3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

# --- Section: Array Creation Examples ---

In [8]:
# np.array: create array from python list
marks = np.array([75, 82, 90, 68, 88])
print(marks)

[75 82 90 68 88]


In [9]:
# np.zeros: 1D array of zeros
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [10]:
# np.zeros: 2D array of zeros
a = np.zeros((2, 3))
print(a)


[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# np.ones: 2D array of ones
a = np.ones((2, 3))
print(a)


[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# np.full: array filled with a specific value (7)
a = np.full((2, 3), 7)
print(a)


[[7 7 7]
 [7 7 7]]


In [13]:
# np.arange: range from 1 to 10
a = np.arange(1, 11)
print(a)


[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
# np.arange: range with step size of 5
a = np.arange(0, 20, 5)
print(a)

[ 0  5 10 15]


In [15]:
# np.linspace: 5 evenly spaced values between 0 and 10
a = np.linspace(0, 10, 5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [16]:
# np.eye: 3x3 identity matrix
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
